/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4e34c78fa055
 */

import { streamingProfilesUpdateStreamingProfile } from "../../funcs/streamingProfilesUpdateStreamingProfile.js";
import { UpdateStreamingProfileRequest$zodSchema } from "../../models/updatestreamingprofileop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateStreamingProfileRequest$zodSchema,
};

export const tool$streamingProfilesUpdateStreamingProfile: ToolDefinition<
  typeof args
> = {
  name: "update-streaming-profile",
  description:
    `Modifies an existing adaptive streaming profile's configuration`,
  scopes: ["builder"],
  annotations: {
    "title": "Update Streaming Profile",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await streamingProfilesUpdateStreamingProfile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
