/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 32b56e97ded2
 */

import { transformationsGetTransformation } from "../../funcs/transformationsGetTransformation.js";
import { GetTransformationRequest$zodSchema } from "../../models/gettransformationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTransformationRequest$zodSchema,
};

export const tool$transformationsGetTransformation: ToolDefinition<
  typeof args
> = {
  name: "get-transformation-details",
  description: `Retrieves details of a specific transformation

Retrieves details for a named or unnamed transformation.
`,
  scopes: ["admin"],
  annotations: {
    "title": "Get Transformation Details",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transformationsGetTransformation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
