/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8051ff62d868
 */

import { transformationsUpdateTransformation } from "../../funcs/transformationsUpdateTransformation.js";
import { UpdateTransformationRequest$zodSchema } from "../../models/updatetransformationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateTransformationRequest$zodSchema,
};

export const tool$transformationsUpdateTransformation: ToolDefinition<
  typeof args
> = {
  name: "update-transformation",
  description: `Updates the definition of an existing transformation

Updates a named or unnamed transformation.
`,
  scopes: ["admin"],
  annotations: {
    "title": "Update Transformation",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transformationsUpdateTransformation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
