/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3c089fceea5e
 */

import { transformationsDeleteTransformation } from "../../funcs/transformationsDeleteTransformation.js";
import { DeleteTransformationRequest$zodSchema } from "../../models/deletetransformationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteTransformationRequest$zodSchema,
};

export const tool$transformationsDeleteTransformation: ToolDefinition<
  typeof args
> = {
  name: "delete-transformation",
  description: `Deletes a named transformation from your account

Delete a named or unnamed transformation. Optionally invalidate derived resources generated using the named transformation.
`,
  scopes: ["admin"],
  annotations: {
    "title": "Delete Transformation",
    "destructiveHint": true,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transformationsDeleteTransformation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
