/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { transformationsCreateTransformation } from "../../funcs/transformationsCreateTransformation.js";
import { CreateRequest$zodSchema } from "../../models/createrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  transformation: z.string().describe(
    "The valid transformation name to create.\n"
      + "",
  ),
  create_request: CreateRequest$zodSchema,
};

export const tool$transformationsCreateTransformation: ToolDefinition<
  typeof args
> = {
  name: "create-transformation",
  description:
    `Creates a new named transformation (assigning a custom name to a set of transformation

Creates a new named transformation with the given name and transformation string.
`,
  scopes: ["admin"],
  annotations: {
    "title": "Create Transformation",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transformationsCreateTransformation(
      client,
      args.transformation,
      args.create_request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
