/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 86830305f9cf
 */

import { transformationsListTransformations } from "../../funcs/transformationsListTransformations.js";
import { ListTransformationsRequest$zodSchema } from "../../models/listtransformationsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListTransformationsRequest$zodSchema.optional(),
};

export const tool$transformationsListTransformations: ToolDefinition<
  typeof args
> = {
  name: "list-transformations",
  description:
    `Lists all transformation definitions in your account, including named transformations

Retrieves a list of all transformations, which can be filtered to show either only named or unnamed transformations.
`,
  scopes: ["admin"],
  annotations: {
    "title": "List Transformations",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transformationsListTransformations(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
