/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { triggersUpdateTrigger } from "../../funcs/triggersUpdateTrigger.js";
import { UpdateTriggerRequestBody$zodSchema } from "../../models/updatetriggerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
  RequestBody: UpdateTriggerRequestBody$zodSchema,
};

export const tool$triggersUpdateTrigger: ToolDefinition<typeof args> = {
  name: "update-trigger",
  description:
    `Updates the callback URL of an existing webhook trigger in your Cloudinary account

Updates a notification URL for a trigger.`,
  scopes: ["admin"],
  annotations: {
    "title": "Update Trigger",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await triggersUpdateTrigger(
      client,
      args.id,
      args.RequestBody,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
