/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0bedcb0b91e0
 */

import { triggersUpdateTrigger } from "../../funcs/triggersUpdateTrigger.js";
import { UpdateTriggerRequestRequest$zodSchema } from "../../models/updatetriggerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateTriggerRequestRequest$zodSchema,
};

export const tool$triggersUpdateTrigger: ToolDefinition<typeof args> = {
  name: "update-trigger",
  description:
    `Updates the callback URL of an existing webhook trigger in your Cloudinary account

Updates a notification URL for a trigger.`,
  scopes: ["admin"],
  annotations: {
    "title": "Update Trigger",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await triggersUpdateTrigger(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
