/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { triggersDeleteTrigger } from "../../funcs/triggersDeleteTrigger.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$triggersDeleteTrigger: ToolDefinition<typeof args> = {
  name: "delete-trigger",
  description: `Deletes a notification trigger

Deletes a trigger.`,
  scopes: ["admin"],
  annotations: {
    "title": "Delete Trigger",
    "destructiveHint": true,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await triggersDeleteTrigger(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
