/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b6710d7af609
 */

import { triggersTestTrigger } from "../../funcs/triggersTestTrigger.js";
import { TestTriggerRequestRequest$zodSchema } from "../../models/testtriggerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TestTriggerRequestRequest$zodSchema,
};

export const tool$triggersTestTrigger: ToolDefinition<typeof args> = {
  name: "test-trigger",
  description: `Tests an existing trigger's filter against sample data

Evaluates an existing trigger's filter against provided sample data.
Use this endpoint to verify that a trigger's filter will match expected events.
`,
  scopes: ["admin"],
  annotations: {
    "title": "Test Trigger Filter",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await triggersTestTrigger(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
