/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uploadMappingsCreateUploadMapping } from "../../funcs/uploadMappingsCreateUploadMapping.js";
import { CreateUploadMappingRequest$zodSchema } from "../../models/createuploadmappingop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateUploadMappingRequest$zodSchema,
};

export const tool$uploadMappingsCreateUploadMapping: ToolDefinition<
  typeof args
> = {
  name: "create-upload-mapping",
  description: `Creates a new upload mapping

Creates a new upload mapping for the specified folder`,
  scopes: ["builder"],
  annotations: {
    "title": "Create Upload Mapping",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await uploadMappingsCreateUploadMapping(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
