/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 798d000ef5fd
 */

import { uploadPresetsListUploadPresets } from "../../funcs/uploadPresetsListUploadPresets.js";
import { ListUploadPresetsRequest$zodSchema } from "../../models/listuploadpresetsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListUploadPresetsRequest$zodSchema.optional(),
};

export const tool$uploadPresetsListUploadPresets: ToolDefinition<typeof args> =
  {
    name: "list-upload-presets",
    description: `Lists all upload presets configured in the account`,
    scopes: ["builder"],
    annotations: {
      "title": "List Upload Presets",
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await uploadPresetsListUploadPresets(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
