/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 400f04c7187f
 */

import { uploadPresetsUpdateUploadPreset } from "../../funcs/uploadPresetsUpdateUploadPreset.js";
import { UpdateUploadPresetRequest$zodSchema } from "../../models/updateuploadpresetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateUploadPresetRequest$zodSchema,
};

export const tool$uploadPresetsUpdateUploadPreset: ToolDefinition<typeof args> =
  {
    name: "update-upload-preset",
    description: `Updates an existing upload preset's configuration settings`,
    scopes: ["builder"],
    annotations: {
      "title": "Update Upload Preset",
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await uploadPresetsUpdateUploadPreset(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
