/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 11db1edd5083
 */

import { uploadMappingsListUploadMappings } from "../../funcs/uploadMappingsListUploadMappings.js";
import { ListUploadMappingsRequest$zodSchema } from "../../models/listuploadmappingsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListUploadMappingsRequest$zodSchema.optional(),
};

export const tool$uploadMappingsListUploadMappings: ToolDefinition<
  typeof args
> = {
  name: "list-upload-mappings",
  description:
    `Retrieves a list of all upload mapping rules configured in your Cloudinary product environment

Returns a list of all upload mappings defined for your account.
Upload mappings allow you to map an upload preset to a specific folder and URL template.
`,
  scopes: ["builder"],
  annotations: {
    "title": "List Upload Mappings",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await uploadMappingsListUploadMappings(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
