/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uploadPresetsCreateUploadPreset } from "../../funcs/uploadPresetsCreateUploadPreset.js";
import { UploadPreset$zodSchema } from "../../models/uploadpreset.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UploadPreset$zodSchema,
};

export const tool$uploadPresetsCreateUploadPreset: ToolDefinition<typeof args> =
  {
    name: "create-upload-preset",
    description:
      `Creates a new upload preset with specified configuration settings`,
    scopes: ["builder"],
    annotations: {
      "title": "Create Upload Preset",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await uploadPresetsCreateUploadPreset(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
