/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { uploadPresetsListUploadPresets } from "../../funcs/uploadPresetsListUploadPresets.js";
import {
  Direction$zodSchema,
  OrderBy$zodSchema,
} from "../../models/listuploadpresetsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  order_by: OrderBy$zodSchema.optional(),
  direction: Direction$zodSchema.optional(),
  next_cursor: z.string().describe(
    "The cursor for pagination. Use the next_cursor value from a previous response to get the next page of results.",
  ).optional(),
};

export const tool$uploadPresetsListUploadPresets: ToolDefinition<typeof args> =
  {
    name: "list-upload-presets",
    description: `Lists all upload presets configured in the account`,
    scopes: ["builder"],
    annotations: {
      "title": "List Upload Presets",
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await uploadPresetsListUploadPresets(
        client,
        args.order_by,
        args.direction,
        args.next_cursor,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
