/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e0910cc98ac5
 */

import { uploadMappingsDeleteUploadMapping } from "../../funcs/uploadMappingsDeleteUploadMapping.js";
import { DeleteUploadMappingRequest$zodSchema } from "../../models/deleteuploadmappingop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteUploadMappingRequest$zodSchema,
};

export const tool$uploadMappingsDeleteUploadMapping: ToolDefinition<
  typeof args
> = {
  name: "delete-upload-mapping",
  description: `Deletes a folder upload mapping

Permanently deletes the upload mapping for the specified folder`,
  scopes: ["builder"],
  annotations: {
    "title": "Delete Upload Mapping",
    "destructiveHint": true,
    "idempotentHint": true,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await uploadMappingsDeleteUploadMapping(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
