/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1c8ec47f5378
 */

import { uploadPresetsDeleteUploadPreset } from "../../funcs/uploadPresetsDeleteUploadPreset.js";
import { DeleteUploadPresetRequest$zodSchema } from "../../models/deleteuploadpresetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteUploadPresetRequest$zodSchema,
};

export const tool$uploadPresetsDeleteUploadPreset: ToolDefinition<typeof args> =
  {
    name: "delete-upload-preset",
    description: `Deletes an upload preset from the account`,
    scopes: ["builder"],
    annotations: {
      "title": "Delete Upload Preset",
      "destructiveHint": true,
      "idempotentHint": true,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await uploadPresetsDeleteUploadPreset(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
