workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    CloudinaryEnvConfig-MCP-OAS:
        inputs:
            - location: https://cloudinary.github.io/api-schemas/environment-config/schema.yml
        overlays:
            - location: https://cloudinary.github.io/api-schemas/overlays/security-scheme-cloud-overlay.yaml
            - location: https://cloudinary.github.io/api-schemas/overlays/cloud-name-overlay.yml
            - location: https://cloudinary.github.io/api-schemas/overlays/mcp-disabled.yml
            - location: https://cloudinary.github.io/api-schemas/overlays/remove-mcp-description.yml
            - location: https://cloudinary.github.io/api-schemas/overlays/signature-optional-overlay.yml
        registry:
            location: registry.speakeasyapi.dev/cloudinary/cloudinary/cloudinary-env-config-mcp-oas
targets:
    cloudinary-env-config-mcp:
        target: mcp-typescript
        source: CloudinaryEnvConfig-MCP-OAS
        publish:
            npm:
                token: $npm_token
