/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of access control to apply to the asset.
 */
export const AccessType$zodSchema = z.enum([
  "token",
  "anonymous",
]).describe("The type of access control to apply to the asset.");

export type AccessType = z.infer<typeof AccessType$zodSchema>;

/**
 * Access control rule that defines when and how the asset can be accessed.
 */
export type AccessControlItem = {
  access_type: AccessType;
  key?: string | undefined;
  start?: string | undefined;
  end?: string | undefined;
};

export const AccessControlItem$zodSchema: z.ZodType<
  AccessControlItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  access_type: AccessType$zodSchema,
  end: z.string().optional(),
  key: z.string().optional(),
  start: z.string().optional(),
}).describe(
  "Access control rule that defines when and how the asset can be accessed.",
);
