/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of access control to apply to the asset.
 */
export const AccessType = {
  Token: "token",
  Anonymous: "anonymous",
} as const;
/**
 * The type of access control to apply to the asset.
 */
export type AccessType = ClosedEnum<typeof AccessType>;

export const AccessType$zodSchema = z.enum([
  "token",
  "anonymous",
]).describe("The type of access control to apply to the asset.");

/**
 * Access control rule that defines when and how the asset can be accessed.
 */
export type AccessControlItem = {
  access_type: AccessType;
  key?: string | undefined;
  start?: string | undefined;
  end?: string | undefined;
};

export const AccessControlItem$zodSchema: z.ZodType<AccessControlItem> = z
  .object({
    access_type: AccessType$zodSchema,
    end: z.string().optional(),
    key: z.string().optional(),
    start: z.string().optional(),
  }).describe(
    "Access control rule that defines when and how the asset can be accessed.",
  );
