/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { TriggerInfo, TriggerInfo$zodSchema } from "./triggerinfo.js";

export type CreateTriggerGlobals = { cloud_name?: string | undefined };

export const CreateTriggerGlobals$zodSchema: z.ZodType<
  CreateTriggerGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type CreateTriggerRequest = { uri: string; event_type: string };

export const CreateTriggerRequest$zodSchema: z.ZodType<
  CreateTriggerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  event_type: z.string(),
  uri: z.string(),
});

export type CreateTriggerResponse = TriggerInfo | ApiError;

export const CreateTriggerResponse$zodSchema: z.ZodType<
  CreateTriggerResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  TriggerInfo$zodSchema,
  ApiError$zodSchema,
]);
