/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f7e150ddbf2a
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  StreamingProfileDataResponse,
  StreamingProfileDataResponse$zodSchema,
} from "./streamingprofiledataresponse.js";

export type CreateStreamingProfileGlobals = { cloud_name?: string | undefined };

export const CreateStreamingProfileGlobals$zodSchema: z.ZodType<
  CreateStreamingProfileGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type CreateStreamingProfileResponse =
  | StreamingProfileDataResponse
  | ApiError;

export const CreateStreamingProfileResponse$zodSchema: z.ZodType<
  CreateStreamingProfileResponse
> = z.union([
  StreamingProfileDataResponse$zodSchema,
  ApiError$zodSchema,
]);
