/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  UploadMappingCreateResponse,
  UploadMappingCreateResponse$zodSchema,
} from "./uploadmappingcreateresponse.js";

export type CreateUploadMappingGlobals = { cloud_name?: string | undefined };

export const CreateUploadMappingGlobals$zodSchema: z.ZodType<
  CreateUploadMappingGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type CreateUploadMappingResponse =
  | UploadMappingCreateResponse
  | ApiError;

export const CreateUploadMappingResponse$zodSchema: z.ZodType<
  CreateUploadMappingResponse
> = z.union([
  UploadMappingCreateResponse$zodSchema,
  ApiError$zodSchema,
]);
