/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3110e63ed474
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  UploadPresetCreateResponse,
  UploadPresetCreateResponse$zodSchema,
} from "./uploadpresetcreateresponse.js";

export type CreateUploadPresetGlobals = { cloud_name?: string | undefined };

export const CreateUploadPresetGlobals$zodSchema: z.ZodType<
  CreateUploadPresetGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type CreateUploadPresetResponse = UploadPresetCreateResponse | ApiError;

export const CreateUploadPresetResponse$zodSchema: z.ZodType<
  CreateUploadPresetResponse
> = z.union([
  UploadPresetCreateResponse$zodSchema,
  ApiError$zodSchema,
]);
