/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type CreateUploadPresetGlobals = { cloud_name?: string | undefined };

export const CreateUploadPresetGlobals$zodSchema: z.ZodType<
  CreateUploadPresetGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

/**
 * upload preset created
 */
export type CreateUploadPresetResponseBody = {
  name: string;
  message: string;
  external_id: string;
};

export const CreateUploadPresetResponseBody$zodSchema: z.ZodType<
  CreateUploadPresetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_id: z.string(),
  message: z.string(),
  name: z.string(),
}).describe("upload preset created");

export type CreateUploadPresetResponse =
  | CreateUploadPresetResponseBody
  | ApiError;

export const CreateUploadPresetResponse$zodSchema: z.ZodType<
  CreateUploadPresetResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => CreateUploadPresetResponseBody$zodSchema),
  ApiError$zodSchema,
]);
