/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type CreateUploadMappingGlobals = { cloud_name?: string | undefined };

export const CreateUploadMappingGlobals$zodSchema: z.ZodType<
  CreateUploadMappingGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type CreateUploadMappingRequest = { folder: string; template: string };

export const CreateUploadMappingRequest$zodSchema: z.ZodType<
  CreateUploadMappingRequest
> = z.object({
  folder: z.string(),
  template: z.string(),
});

/**
 * Upload mapping created successfully
 */
export type CreateUploadMappingResponseBody = {
  message: string;
  folder: string;
  external_id: string;
};

export const CreateUploadMappingResponseBody$zodSchema: z.ZodType<
  CreateUploadMappingResponseBody
> = z.object({
  external_id: z.string(),
  folder: z.string(),
  message: z.string(),
}).describe("Upload mapping created successfully");

export type CreateUploadMappingResponse =
  | CreateUploadMappingResponseBody
  | ApiError;

export const CreateUploadMappingResponse$zodSchema: z.ZodType<
  CreateUploadMappingResponse
> = z.union([
  z.lazy(() => CreateUploadMappingResponseBody$zodSchema),
  ApiError$zodSchema,
]);
