/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { CreateRequest, CreateRequest$zodSchema } from "./createrequest.js";

export type CreateTransformationGlobals = { cloud_name?: string | undefined };

export const CreateTransformationGlobals$zodSchema: z.ZodType<
  CreateTransformationGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type CreateTransformationRequest = {
  transformation: string;
  create_request: CreateRequest;
};

export const CreateTransformationRequest$zodSchema: z.ZodType<
  CreateTransformationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  create_request: CreateRequest$zodSchema,
  transformation: z.string().describe(
    "The valid transformation name to create.\n"
      + "",
  ),
});

/**
 * Transformation created
 */
export type CreateTransformationResponseBody = { message?: string | undefined };

export const CreateTransformationResponseBody$zodSchema: z.ZodType<
  CreateTransformationResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
}).describe("Transformation created");

export type CreateTransformationResponse =
  | ApiError
  | CreateTransformationResponseBody;

export const CreateTransformationResponse$zodSchema: z.ZodType<
  CreateTransformationResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  z.lazy(() => CreateTransformationResponseBody$zodSchema),
]);
