/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  StreamingProfile,
  StreamingProfile$zodSchema,
} from "./streamingprofile.js";

export type CreateStreamingProfileGlobals = { cloud_name?: string | undefined };

export const CreateStreamingProfileGlobals$zodSchema: z.ZodType<
  CreateStreamingProfileGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

/**
 * Streaming profile created
 */
export type CreateStreamingProfileResponseBody = { data: StreamingProfile };

export const CreateStreamingProfileResponseBody$zodSchema: z.ZodType<
  CreateStreamingProfileResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: StreamingProfile$zodSchema,
}).describe("Streaming profile created");

export type CreateStreamingProfileResponse =
  | CreateStreamingProfileResponseBody
  | ApiError;

export const CreateStreamingProfileResponse$zodSchema: z.ZodType<
  CreateStreamingProfileResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => CreateStreamingProfileResponseBody$zodSchema),
  ApiError$zodSchema,
]);
