/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateRequest = {
  transformation: string;
  allowed_for_strict?: boolean | undefined;
};

export const CreateRequest$zodSchema: z.ZodType<
  CreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  allowed_for_strict: z.boolean().optional(),
  transformation: z.string(),
});
