/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type DeleteTransformationGlobals = { cloud_name?: string | undefined };

export const DeleteTransformationGlobals$zodSchema: z.ZodType<
  DeleteTransformationGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteTransformationRequest = {
  transformation: string;
  invalidate?: boolean | undefined;
};

export const DeleteTransformationRequest$zodSchema: z.ZodType<
  DeleteTransformationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  invalidate: z.boolean().describe(
    "Invalidate derived resources generated using the deleted transformation from CDN.",
  ).optional(),
  transformation: z.string().describe(
    "The transformation identifier. Can be either a named transformation (e.g., 'small_profile_thumbnail') or a transformation string (e.g., 'w_100,h_150,c_fill,g_auto').\n"
      + "",
  ),
});

/**
 * Transformation deleted
 */
export type DeleteTransformationResponseBody = { message?: string | undefined };

export const DeleteTransformationResponseBody$zodSchema: z.ZodType<
  DeleteTransformationResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
}).describe("Transformation deleted");

export type DeleteTransformationResponse =
  | ApiError
  | DeleteTransformationResponseBody;

export const DeleteTransformationResponse$zodSchema: z.ZodType<
  DeleteTransformationResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  z.lazy(() => DeleteTransformationResponseBody$zodSchema),
]);
