/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type DeleteStreamingProfileGlobals = { cloud_name?: string | undefined };

export const DeleteStreamingProfileGlobals$zodSchema: z.ZodType<
  DeleteStreamingProfileGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteStreamingProfileRequest = { name: string };

export const DeleteStreamingProfileRequest$zodSchema: z.ZodType<
  DeleteStreamingProfileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

/**
 * Streaming profile deleted or reverted
 */
export type DeleteStreamingProfileResponseBody = { message: string };

export const DeleteStreamingProfileResponseBody$zodSchema: z.ZodType<
  DeleteStreamingProfileResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
}).describe("Streaming profile deleted or reverted");

export type DeleteStreamingProfileResponse =
  | DeleteStreamingProfileResponseBody
  | ApiError;

export const DeleteStreamingProfileResponse$zodSchema: z.ZodType<
  DeleteStreamingProfileResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => DeleteStreamingProfileResponseBody$zodSchema),
  ApiError$zodSchema,
]);
