/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type DeleteUploadMappingGlobals = { cloud_name?: string | undefined };

export const DeleteUploadMappingGlobals$zodSchema: z.ZodType<
  DeleteUploadMappingGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteUploadMappingRequest = { folder: string };

export const DeleteUploadMappingRequest$zodSchema: z.ZodType<
  DeleteUploadMappingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  folder: z.string().describe("The folder name of the mapping to delete"),
});

/**
 * Upload mapping deleted successfully
 */
export type DeleteUploadMappingResponseBody = {
  message: string;
  external_id: string;
};

export const DeleteUploadMappingResponseBody$zodSchema: z.ZodType<
  DeleteUploadMappingResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_id: z.string(),
  message: z.string(),
}).describe("Upload mapping deleted successfully");

export type DeleteUploadMappingResponse =
  | DeleteUploadMappingResponseBody
  | ApiError;

export const DeleteUploadMappingResponse$zodSchema: z.ZodType<
  DeleteUploadMappingResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => DeleteUploadMappingResponseBody$zodSchema),
  ApiError$zodSchema,
]);
