/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type DeleteUploadPresetGlobals = { cloud_name?: string | undefined };

export const DeleteUploadPresetGlobals$zodSchema: z.ZodType<
  DeleteUploadPresetGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type DeleteUploadPresetRequest = { name: string };

export const DeleteUploadPresetRequest$zodSchema: z.ZodType<
  DeleteUploadPresetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

/**
 * upload preset deleted
 */
export type DeleteUploadPresetResponseBody = {
  message: string;
  external_id: string;
};

export const DeleteUploadPresetResponseBody$zodSchema: z.ZodType<
  DeleteUploadPresetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_id: z.string(),
  message: z.string(),
}).describe("upload preset deleted");

export type DeleteUploadPresetResponse =
  | DeleteUploadPresetResponseBody
  | ApiError;

export const DeleteUploadPresetResponse$zodSchema: z.ZodType<
  DeleteUploadPresetResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => DeleteUploadPresetResponseBody$zodSchema),
  ApiError$zodSchema,
]);
