/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  StreamingProfile,
  StreamingProfile$zodSchema,
} from "./streamingprofile.js";

export type GetStreamingProfileGlobals = { cloud_name?: string | undefined };

export const GetStreamingProfileGlobals$zodSchema: z.ZodType<
  GetStreamingProfileGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GetStreamingProfileRequest = { name: string };

export const GetStreamingProfileRequest$zodSchema: z.ZodType<
  GetStreamingProfileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

/**
 * Streaming profile retrieved
 */
export type GetStreamingProfileResponseBody = { data: StreamingProfile };

export const GetStreamingProfileResponseBody$zodSchema: z.ZodType<
  GetStreamingProfileResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: StreamingProfile$zodSchema,
}).describe("Streaming profile retrieved");

export type GetStreamingProfileResponse =
  | GetStreamingProfileResponseBody
  | ApiError;

export const GetStreamingProfileResponse$zodSchema: z.ZodType<
  GetStreamingProfileResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetStreamingProfileResponseBody$zodSchema),
  ApiError$zodSchema,
]);
