/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  StreamingProfile,
  StreamingProfile$zodSchema,
} from "./streamingprofile.js";

export type GetStreamingProfilesGlobals = { cloud_name?: string | undefined };

export const GetStreamingProfilesGlobals$zodSchema: z.ZodType<
  GetStreamingProfilesGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GetStreamingProfilesRequest = {};

export const GetStreamingProfilesRequest$zodSchema: z.ZodType<
  GetStreamingProfilesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});

/**
 * Streaming profiles retrieved
 */
export type GetStreamingProfilesResponseBody = {
  data: Array<StreamingProfile>;
};

export const GetStreamingProfilesResponseBody$zodSchema: z.ZodType<
  GetStreamingProfilesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(StreamingProfile$zodSchema),
}).describe("Streaming profiles retrieved");

export type GetStreamingProfilesResponse =
  | GetStreamingProfilesResponseBody
  | ApiError;

export const GetStreamingProfilesResponse$zodSchema: z.ZodType<
  GetStreamingProfilesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetStreamingProfilesResponseBody$zodSchema),
  ApiError$zodSchema,
]);
