/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { UploadPreset, UploadPreset$zodSchema } from "./uploadpreset.js";

export type GetUploadPresetGlobals = { cloud_name?: string | undefined };

export const GetUploadPresetGlobals$zodSchema: z.ZodType<
  GetUploadPresetGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type GetUploadPresetRequest = { name: string };

export const GetUploadPresetRequest$zodSchema: z.ZodType<
  GetUploadPresetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

export type GetUploadPresetResponse = ApiError | UploadPreset;

export const GetUploadPresetResponse$zodSchema: z.ZodType<
  GetUploadPresetResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  UploadPreset$zodSchema,
]);
