/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { UploadMapping, UploadMapping$zodSchema } from "./uploadmapping.js";

export type ListUploadMappingsGlobals = { cloud_name?: string | undefined };

export const ListUploadMappingsGlobals$zodSchema: z.ZodType<
  ListUploadMappingsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListUploadMappingsRequest = {
  folder?: string | undefined;
  next_cursor?: string | undefined;
  max_results?: number | undefined;
};

export const ListUploadMappingsRequest$zodSchema: z.ZodType<
  ListUploadMappingsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  folder: z.string().describe(
    "Get details of a specific mapping by folder name",
  ).optional(),
  max_results: z.number().int().default(10).describe(
    "The maximum number of results to return. Default is 10.",
  ),
  next_cursor: z.string().describe(
    "The cursor for pagination. Use the next_cursor value from a previous response to get the next page of results.",
  ).optional(),
});

/**
 * List response
 */
export type ResponseBody = {
  mappings: Array<UploadMapping>;
  total_entries: number;
  next_cursor?: string | undefined;
};

export const ResponseBody$zodSchema: z.ZodType<
  ResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  mappings: z.array(UploadMapping$zodSchema),
  next_cursor: z.string().optional(),
  total_entries: z.number().int(),
}).describe("List response");

/**
 * Upload mappings retrieved successfully
 */
export type ListUploadMappingsResponseBody = UploadMapping | ResponseBody;

export const ListUploadMappingsResponseBody$zodSchema: z.ZodType<
  ListUploadMappingsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  UploadMapping$zodSchema,
  z.lazy(() => ResponseBody$zodSchema),
]).describe("Upload mappings retrieved successfully");

export type ListUploadMappingsResponse =
  | ApiError
  | UploadMapping
  | ResponseBody;

export const ListUploadMappingsResponse$zodSchema: z.ZodType<
  ListUploadMappingsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  z.union([
    UploadMapping$zodSchema,
    z.lazy(() => ResponseBody$zodSchema),
  ]),
]);
