/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { TriggerInfo, TriggerInfo$zodSchema } from "./triggerinfo.js";

export type ListTriggerGlobals = { cloud_name?: string | undefined };

export const ListTriggerGlobals$zodSchema: z.ZodType<
  ListTriggerGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ListTriggerRequest = { event_type?: string | undefined };

export const ListTriggerRequest$zodSchema: z.ZodType<
  ListTriggerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  event_type: z.string().describe(
    "The type of event that will trigger the notification response.",
  ).optional(),
});

/**
 * List response
 */
export type ListTriggerResponseBody = {
  triggers: Array<TriggerInfo>;
  total: number;
};

export const ListTriggerResponseBody$zodSchema: z.ZodType<
  ListTriggerResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  total: z.number().int(),
  triggers: z.array(TriggerInfo$zodSchema),
}).describe("List response");

export type ListTriggerResponse = ListTriggerResponseBody | ApiError;

export const ListTriggerResponse$zodSchema: z.ZodType<
  ListTriggerResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ListTriggerResponseBody$zodSchema),
  ApiError$zodSchema,
]);
