/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TransformationSummary,
  TransformationSummary$zodSchema,
} from "./transformationsummary.js";

export type ListResponse = {
  transformations?: Array<TransformationSummary> | undefined;
  next_cursor?: string | null | undefined;
};

export const ListResponse$zodSchema: z.ZodType<
  ListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  next_cursor: z.string().nullable().optional(),
  transformations: z.array(TransformationSummary$zodSchema).optional(),
});
