/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { UploadPreset, UploadPreset$zodSchema } from "./uploadpreset.js";

export type ListUploadPresetsGlobals = { cloud_name?: string | undefined };

export const ListUploadPresetsGlobals$zodSchema: z.ZodType<
  ListUploadPresetsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export const OrderBy$zodSchema = z.enum([
  "name",
  "id",
  "updated_at",
]);

export type OrderBy = z.infer<typeof OrderBy$zodSchema>;

export const Direction$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type Direction = z.infer<typeof Direction$zodSchema>;

export type ListUploadPresetsRequest = {
  order_by?: OrderBy | undefined;
  direction?: Direction | undefined;
  next_cursor?: string | undefined;
};

export const ListUploadPresetsRequest$zodSchema: z.ZodType<
  ListUploadPresetsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  direction: Direction$zodSchema.optional(),
  next_cursor: z.string().describe(
    "The cursor for pagination. Use the next_cursor value from a previous response to get the next page of results.",
  ).optional(),
  order_by: OrderBy$zodSchema.optional(),
});

/**
 * upload presets retrieved
 */
export type ListUploadPresetsResponseBody = { presets: Array<UploadPreset> };

export const ListUploadPresetsResponseBody$zodSchema: z.ZodType<
  ListUploadPresetsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  presets: z.array(UploadPreset$zodSchema),
}).describe("upload presets retrieved");

export type ListUploadPresetsResponse =
  | ListUploadPresetsResponseBody
  | ApiError;

export const ListUploadPresetsResponse$zodSchema: z.ZodType<
  ListUploadPresetsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ListUploadPresetsResponseBody$zodSchema),
  ApiError$zodSchema,
]);
