/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dc5c93bb7238
 */

import * as z from "zod";
import {
  UploadMappingInput,
  UploadMappingInput$zodSchema,
} from "./uploadmappinginput.js";

export type ReplaceUploadMappingsRequest = {
  mappings: Array<UploadMappingInput>;
};

export const ReplaceUploadMappingsRequest$zodSchema: z.ZodType<
  ReplaceUploadMappingsRequest
> = z.object({
  mappings: z.array(UploadMappingInput$zodSchema),
});
