/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type ReplaceUploadMappingsGlobals = { cloud_name?: string | undefined };

export const ReplaceUploadMappingsGlobals$zodSchema: z.ZodType<
  ReplaceUploadMappingsGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type Mapping = { folder: string; template: string };

export const Mapping$zodSchema: z.ZodType<Mapping, z.ZodTypeDef, unknown> = z
  .object({
    folder: z.string(),
    template: z.string(),
  });

export type ReplaceUploadMappingsRequest = { mappings: Array<Mapping> };

export const ReplaceUploadMappingsRequest$zodSchema: z.ZodType<
  ReplaceUploadMappingsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  mappings: z.array(z.lazy(() => Mapping$zodSchema)),
});

/**
 * upload mappings replaced
 */
export type ReplaceUploadMappingsResponseBody = { message: string };

export const ReplaceUploadMappingsResponseBody$zodSchema: z.ZodType<
  ReplaceUploadMappingsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
}).describe("upload mappings replaced");

export type ReplaceUploadMappingsResponse =
  | ReplaceUploadMappingsResponseBody
  | ApiError;

export const ReplaceUploadMappingsResponse$zodSchema: z.ZodType<
  ReplaceUploadMappingsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ReplaceUploadMappingsResponseBody$zodSchema),
  ApiError$zodSchema,
]);
