/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7b1ca2a90c4a
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  MessageResponse,
  MessageResponse$zodSchema,
} from "./messageresponse.js";

export type ReplaceUploadMappingsGlobals = { cloud_name?: string | undefined };

export const ReplaceUploadMappingsGlobals$zodSchema: z.ZodType<
  ReplaceUploadMappingsGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type ReplaceUploadMappingsResponse = MessageResponse | ApiError;

export const ReplaceUploadMappingsResponse$zodSchema: z.ZodType<
  ReplaceUploadMappingsResponse
> = z.union([
  MessageResponse$zodSchema,
  ApiError$zodSchema,
]);
