/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eee6fc74c73a
 */

import * as z from "zod";

export type ResponsiveBreakpoint = {
  create_derived?: boolean | undefined;
  max_width?: number | undefined;
  min_width?: number | undefined;
  bytes_step?: number | undefined;
  max_images?: number | undefined;
  transformation?: string | undefined;
};

export const ResponsiveBreakpoint$zodSchema: z.ZodType<ResponsiveBreakpoint> = z
  .object({
    bytes_step: z.int().optional(),
    create_derived: z.boolean().optional(),
    max_images: z.int().optional(),
    max_width: z.int().optional(),
    min_width: z.int().optional(),
    transformation: z.string().optional(),
  });
