/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type StreamingProfileCreate = {
  name: string;
  display_name?: string | null | undefined;
  representations: string;
};

export const StreamingProfileCreate$zodSchema: z.ZodType<
  StreamingProfileCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.string().nullable().optional(),
  name: z.string(),
  representations: z.string(),
});
