/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type StreamingProfileUpdate = {
  display_name?: string | null | undefined;
  representations: string;
};

export const StreamingProfileUpdate$zodSchema: z.ZodType<
  StreamingProfileUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.string().nullable().optional(),
  representations: z.string(),
});
