/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Representation = {
  transformation?: Array<{ [k: string]: any }> | undefined;
};

export const Representation$zodSchema: z.ZodType<
  Representation,
  z.ZodTypeDef,
  unknown
> = z.object({
  transformation: z.array(z.record(z.any())).optional(),
});

export type StreamingProfile = {
  external_id: string;
  name: string;
  display_name?: string | null | undefined;
  predefined: boolean;
  representations?: Array<Representation> | undefined;
};

export const StreamingProfile$zodSchema: z.ZodType<
  StreamingProfile,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.string().nullable().optional(),
  external_id: z.string(),
  name: z.string(),
  predefined: z.boolean(),
  representations: z.array(z.lazy(() => Representation$zodSchema)).optional(),
});
