/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type TestTriggerGlobals = { cloud_name?: string | undefined };

export const TestTriggerGlobals$zodSchema: z.ZodType<TestTriggerGlobals> = z
  .object({
    cloud_name: z.string().describe(
      "The cloud name of your product environment.",
    ).optional(),
  });

/**
 * Sample notification data to evaluate the filter against.
 */
export type SampleData = {};

export const SampleData$zodSchema: z.ZodType<SampleData> = z.object({})
  .describe("Sample notification data to evaluate the filter against.");

export type TestTriggerRequestBody = { sample_data?: SampleData | undefined };

export const TestTriggerRequestBody$zodSchema: z.ZodType<
  TestTriggerRequestBody
> = z.object({
  sample_data: z.lazy(() => SampleData$zodSchema).optional(),
});

export type TestTriggerRequest = {
  id: string;
  RequestBody?: TestTriggerRequestBody | undefined;
};

export const TestTriggerRequest$zodSchema: z.ZodType<TestTriggerRequest> = z
  .object({
    RequestBody: z.lazy(() => TestTriggerRequestBody$zodSchema).optional(),
    id: z.string(),
  });

/**
 * Test completed successfully
 */
export type TestTriggerResponseBody = {
  trigger_id: string;
  filter_present: boolean;
  filter_result: boolean;
};

export const TestTriggerResponseBody$zodSchema: z.ZodType<
  TestTriggerResponseBody
> = z.object({
  filter_present: z.boolean(),
  filter_result: z.boolean(),
  trigger_id: z.string(),
}).describe("Test completed successfully");

export type TestTriggerResponse = TestTriggerResponseBody | ApiError;

export const TestTriggerResponse$zodSchema: z.ZodType<TestTriggerResponse> = z
  .union([
    z.lazy(() => TestTriggerResponseBody$zodSchema),
    ApiError$zodSchema,
  ]);
