/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b985c4059dd2
 */

import * as z from "zod";

export type TestTriggerResponse = {
  trigger_id: string;
  filter_present: boolean;
  filter_result: boolean;
};

export const TestTriggerResponse$zodSchema: z.ZodType<TestTriggerResponse> = z
  .object({
    filter_present: z.boolean(),
    filter_result: z.boolean(),
    trigger_id: z.string(),
  });
