/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Info = {
  width?: number | undefined;
  height?: number | undefined;
  crop?: string | undefined;
  gravity?: string | undefined;
};

export const Info$zodSchema: z.ZodType<Info, z.ZodTypeDef, unknown> = z.object({
  crop: z.string().optional(),
  gravity: z.string().optional(),
  height: z.number().int().optional(),
  width: z.number().int().optional(),
});

export type Derived = {
  public_id?: string | undefined;
  resource_type?: string | undefined;
  type?: string | undefined;
  format?: string | undefined;
  url?: string | undefined;
  secure_url?: string | undefined;
  bytes?: number | undefined;
  id?: string | undefined;
};

export const Derived$zodSchema: z.ZodType<Derived, z.ZodTypeDef, unknown> = z
  .object({
    bytes: z.number().int().optional(),
    format: z.string().optional(),
    id: z.string().optional(),
    public_id: z.string().optional(),
    resource_type: z.string().optional(),
    secure_url: z.string().optional(),
    type: z.string().optional(),
    url: z.string().optional(),
  });

export type TransformationInfo = {
  name?: string | undefined;
  allowed_for_strict?: boolean | undefined;
  used?: boolean | undefined;
  named?: boolean | undefined;
  info?: Array<Info> | undefined;
  derived?: Array<Derived> | undefined;
  next_cursor?: string | undefined;
};

export const TransformationInfo$zodSchema: z.ZodType<
  TransformationInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  allowed_for_strict: z.boolean().optional(),
  derived: z.array(z.lazy(() => Derived$zodSchema)).optional(),
  info: z.array(z.lazy(() => Info$zodSchema)).optional(),
  name: z.string().optional(),
  named: z.boolean().optional(),
  next_cursor: z.string().optional(),
  used: z.boolean().optional(),
});
