/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { UriType, UriType$zodSchema } from "./uritype.js";

export type TriggerInfo = {
  id?: string | undefined;
  product_environment_id?: string | undefined;
  uri_type: UriType;
  uri: string;
  event_type?: string | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
};

export const TriggerInfo$zodSchema: z.ZodType<
  TriggerInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).optional(),
  event_type: z.string().optional(),
  id: z.string().optional(),
  product_environment_id: z.string().optional(),
  updated_at: z.string().datetime({ offset: true }).optional(),
  uri: z.string(),
  uri_type: UriType$zodSchema,
});
