/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { UpdateRequest, UpdateRequest$zodSchema } from "./updaterequest.js";

export type UpdateTransformationGlobals = { cloud_name?: string | undefined };

export const UpdateTransformationGlobals$zodSchema: z.ZodType<
  UpdateTransformationGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateTransformationRequest = {
  transformation: string;
  update_request: UpdateRequest;
};

export const UpdateTransformationRequest$zodSchema: z.ZodType<
  UpdateTransformationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  transformation: z.string().describe(
    "The transformation identifier. Can be either a named transformation (e.g., 'small_profile_thumbnail') or a transformation string (e.g., 'w_100,h_150,c_fill,g_auto').\n"
      + "",
  ),
  update_request: UpdateRequest$zodSchema,
});

/**
 * Transformation updated
 */
export type UpdateTransformationResponseBody = { message?: string | undefined };

export const UpdateTransformationResponseBody$zodSchema: z.ZodType<
  UpdateTransformationResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
}).describe("Transformation updated");

export type UpdateTransformationResponse =
  | ApiError
  | UpdateTransformationResponseBody;

export const UpdateTransformationResponse$zodSchema: z.ZodType<
  UpdateTransformationResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ApiError$zodSchema,
  z.lazy(() => UpdateTransformationResponseBody$zodSchema),
]);
