/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import { UploadPreset, UploadPreset$zodSchema } from "./uploadpreset.js";

export type UpdateUploadPresetGlobals = { cloud_name?: string | undefined };

export const UpdateUploadPresetGlobals$zodSchema: z.ZodType<
  UpdateUploadPresetGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateUploadPresetRequest = {
  name: string;
  upload_preset: UploadPreset;
};

export const UpdateUploadPresetRequest$zodSchema: z.ZodType<
  UpdateUploadPresetRequest
> = z.object({
  name: z.string(),
  upload_preset: UploadPreset$zodSchema,
});

/**
 * upload preset updated
 */
export type UpdateUploadPresetResponseBody = {
  message: string;
  external_id: string;
};

export const UpdateUploadPresetResponseBody$zodSchema: z.ZodType<
  UpdateUploadPresetResponseBody
> = z.object({
  external_id: z.string(),
  message: z.string(),
}).describe("upload preset updated");

export type UpdateUploadPresetResponse =
  | UpdateUploadPresetResponseBody
  | ApiError;

export const UpdateUploadPresetResponse$zodSchema: z.ZodType<
  UpdateUploadPresetResponse
> = z.union([
  z.lazy(() => UpdateUploadPresetResponseBody$zodSchema),
  ApiError$zodSchema,
]);
