/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateRequest = {
  unsafe_update?: string | undefined;
  allowed_for_strict?: boolean | undefined;
};

export const UpdateRequest$zodSchema: z.ZodType<
  UpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  allowed_for_strict: z.boolean().optional(),
  unsafe_update: z.string().optional(),
});
