/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";

export type UpdateUploadMappingGlobals = { cloud_name?: string | undefined };

export const UpdateUploadMappingGlobals$zodSchema: z.ZodType<
  UpdateUploadMappingGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateUploadMappingRequest = { folder: string; template: string };

export const UpdateUploadMappingRequest$zodSchema: z.ZodType<
  UpdateUploadMappingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  folder: z.string(),
  template: z.string(),
});

/**
 * Upload mapping updated successfully
 */
export type UpdateUploadMappingResponseBody = {
  message: string;
  external_id: string;
};

export const UpdateUploadMappingResponseBody$zodSchema: z.ZodType<
  UpdateUploadMappingResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_id: z.string(),
  message: z.string(),
}).describe("Upload mapping updated successfully");

export type UpdateUploadMappingResponse =
  | UpdateUploadMappingResponseBody
  | ApiError;

export const UpdateUploadMappingResponse$zodSchema: z.ZodType<
  UpdateUploadMappingResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => UpdateUploadMappingResponseBody$zodSchema),
  ApiError$zodSchema,
]);
