/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d502659f7b62
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  UploadMappingMutationResponse,
  UploadMappingMutationResponse$zodSchema,
} from "./uploadmappingmutationresponse.js";

export type UpdateUploadMappingGlobals = { cloud_name?: string | undefined };

export const UpdateUploadMappingGlobals$zodSchema: z.ZodType<
  UpdateUploadMappingGlobals
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateUploadMappingResponse =
  | UploadMappingMutationResponse
  | ApiError;

export const UpdateUploadMappingResponse$zodSchema: z.ZodType<
  UpdateUploadMappingResponse
> = z.union([
  UploadMappingMutationResponse$zodSchema,
  ApiError$zodSchema,
]);
