/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: adf3ff99f4bd
 */

import * as z from "zod";

export type UpdateRequest = {
  unsafe_update?: string | undefined;
  allowed_for_strict?: boolean | undefined;
};

export const UpdateRequest$zodSchema: z.ZodType<UpdateRequest> = z.object({
  allowed_for_strict: z.boolean().optional(),
  unsafe_update: z.string().optional(),
});
