/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiError, ApiError$zodSchema } from "./apierror.js";
import {
  StreamingProfile,
  StreamingProfile$zodSchema,
} from "./streamingprofile.js";
import {
  StreamingProfileUpdate,
  StreamingProfileUpdate$zodSchema,
} from "./streamingprofileupdate.js";

export type UpdateStreamingProfileGlobals = { cloud_name?: string | undefined };

export const UpdateStreamingProfileGlobals$zodSchema: z.ZodType<
  UpdateStreamingProfileGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().describe("The cloud name of your product environment.")
    .optional(),
});

export type UpdateStreamingProfileRequest = {
  name: string;
  streaming_profile_update: StreamingProfileUpdate;
};

export const UpdateStreamingProfileRequest$zodSchema: z.ZodType<
  UpdateStreamingProfileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  streaming_profile_update: StreamingProfileUpdate$zodSchema,
});

/**
 * Streaming profile updated
 */
export type UpdateStreamingProfileResponseBody = {
  message: string;
  data: StreamingProfile;
};

export const UpdateStreamingProfileResponseBody$zodSchema: z.ZodType<
  UpdateStreamingProfileResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: StreamingProfile$zodSchema,
  message: z.string(),
}).describe("Streaming profile updated");

export type UpdateStreamingProfileResponse =
  | UpdateStreamingProfileResponseBody
  | ApiError;

export const UpdateStreamingProfileResponse$zodSchema: z.ZodType<
  UpdateStreamingProfileResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => UpdateStreamingProfileResponseBody$zodSchema),
  ApiError$zodSchema,
]);
