/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 241bb386b6ef
 */

import * as z from "zod";

export type UploadPresetCreateResponse = {
  message: string;
  name: string;
  external_id: string;
};

export const UploadPresetCreateResponse$zodSchema: z.ZodType<
  UploadPresetCreateResponse
> = z.object({
  external_id: z.string(),
  message: z.string(),
  name: z.string(),
});
