/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Represents an upload mapping
 */
export type UploadMapping = {
  folder: string;
  template: string;
  external_id: string;
  upload_preset_name?: string | null | undefined;
};

export const UploadMapping$zodSchema: z.ZodType<
  UploadMapping,
  z.ZodTypeDef,
  unknown
> = z.object({
  external_id: z.string(),
  folder: z.string(),
  template: z.string(),
  upload_preset_name: z.string().nullable().optional(),
}).describe("Represents an upload mapping");
