/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b516d68684cf
 */

import * as z from "zod";

export type UploadMappingCreateResponse = {
  message: string;
  folder: string;
  external_id: string;
};

export const UploadMappingCreateResponse$zodSchema: z.ZodType<
  UploadMappingCreateResponse
> = z.object({
  external_id: z.string(),
  folder: z.string(),
  message: z.string(),
});
