/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4d89e7e1dd72
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  AccessControlItem,
  AccessControlItem$zodSchema,
} from "./accesscontrolitem.js";
import {
  ResponsiveBreakpoint,
  ResponsiveBreakpoint$zodSchema,
} from "./responsivebreakpoint.js";
import {
  StructuredMetadataParam,
  StructuredMetadataParam$zodSchema,
} from "./structuredmetadataparam.js";
import {
  UploadDeliveryType,
  UploadDeliveryType$zodSchema,
} from "./uploaddeliverytype.js";

/**
 * Configuration object for automatic video transcription with translation options.
 */
export type UploadPresetParsedSettingsAutoTranscription = {
  translate?: Array<string> | undefined;
};

export const UploadPresetParsedSettingsAutoTranscription$zodSchema: z.ZodType<
  UploadPresetParsedSettingsAutoTranscription
> = z.object({
  translate: z.array(z.string()).optional(),
}).describe(
  "Configuration object for automatic video transcription with translation options.",
);

export type UploadPresetParsedSettingsAutoTranscriptionUnion =
  | boolean
  | UploadPresetParsedSettingsAutoTranscription;

export const UploadPresetParsedSettingsAutoTranscriptionUnion$zodSchema:
  z.ZodType<UploadPresetParsedSettingsAutoTranscriptionUnion> = z.union([
    z.boolean(),
    z.lazy(() => UploadPresetParsedSettingsAutoTranscription$zodSchema),
  ]);

/**
 * Deprecated. Use access_control instead. Allows the asset to behave as if it's of the authenticated delivery type while still using the default 'upload' type in delivery URLs. The asset can later be made public by changing its access_mode via the Admin API, without having to update any delivery URLs.
 *
 * @remarks
 *
 * @deprecated enum: The access_mode parameter is no longer supported. To restrict access to assets, you can use the access_control parameter.. Use access_control instead.
 */
export const UploadPresetParsedSettingsAccessMode = {
  Public: "public",
  Authenticated: "authenticated",
} as const;
/**
 * Deprecated. Use access_control instead. Allows the asset to behave as if it's of the authenticated delivery type while still using the default 'upload' type in delivery URLs. The asset can later be made public by changing its access_mode via the Admin API, without having to update any delivery URLs.
 *
 * @remarks
 *
 * @deprecated enum: The access_mode parameter is no longer supported. To restrict access to assets, you can use the access_control parameter.. Use access_control instead.
 */
export type UploadPresetParsedSettingsAccessMode = ClosedEnum<
  typeof UploadPresetParsedSettingsAccessMode
>;

export const UploadPresetParsedSettingsAccessMode$zodSchema = z.enum([
  "public",
  "authenticated",
]).describe(
  "Deprecated. Use access_control instead. Allows the asset to behave as if it's of the authenticated delivery type while still using the default 'upload' type in delivery URLs. The asset can later be made public by changing its access_mode via the Admin API, without having to update any delivery URLs.\n",
);

/**
 * Named region coordinate groups for cropping with region gravity.
 *
 * @remarks
 * Can be a JSON-encoded string or an object. Each region name may contain
 * only letters, numbers, or hyphens, and must have at least two coordinate pairs.
 */
export type UploadPresetParsedSettingsRegions = string | {
  [k: string]: Array<Array<number>>;
};

export const UploadPresetParsedSettingsRegions$zodSchema: z.ZodType<
  UploadPresetParsedSettingsRegions
> = z.union([
  z.string(),
  z.record(z.string(), z.array(z.array(z.int()))),
]).describe(
  "Named region coordinate groups for cropping with region gravity.\nCan be a JSON-encoded string or an object. Each region name may contain\nonly letters, numbers, or hyphens, and must have at least two coordinate pairs.\n",
);

/**
 * Settings to automatically generate breakpoints for responsive images.
 */
export type UploadPresetParsedSettingsResponsiveBreakpoints =
  | Array<ResponsiveBreakpoint>
  | ResponsiveBreakpoint;

export const UploadPresetParsedSettingsResponsiveBreakpoints$zodSchema:
  z.ZodType<UploadPresetParsedSettingsResponsiveBreakpoints> = z.union([
    z.array(ResponsiveBreakpoint$zodSchema),
    ResponsiveBreakpoint$zodSchema,
  ]).describe(
    "Settings to automatically generate breakpoints for responsive images.",
  );

/**
 * Parsed preset configuration settings. Composed from base parameters (stable types) plus parsed serializable fields (arrays/objects instead of strings).
 */
export type UploadPresetParsedSettings = {
  accessibility_analysis?: boolean | undefined;
  asset_folder?: string | undefined;
  async?: boolean | undefined;
  auto_chaptering?: boolean | undefined;
  auto_tagging?: number | undefined;
  auto_transcription?:
    | boolean
    | UploadPresetParsedSettingsAutoTranscription
    | undefined;
  access_control?: Array<AccessControlItem> | undefined;
  access_mode?: UploadPresetParsedSettingsAccessMode | undefined;
  backup?: boolean | undefined;
  background_removal?: string | undefined;
  callback?: string | undefined;
  categorization?: string | undefined;
  cinemagraph_analysis?: boolean | undefined;
  colors?: boolean | undefined;
  detection?: string | undefined;
  discard_original_filename?: boolean | undefined;
  display_name?: string | undefined;
  eager_async?: boolean | undefined;
  eager_notification_url?: string | undefined;
  eval?: string | undefined;
  faces?: boolean | undefined;
  filename_override?: string | undefined;
  folder?: string | undefined;
  format?: string | undefined;
  invalidate?: boolean | undefined;
  media_metadata?: boolean | undefined;
  metadata?: StructuredMetadataParam | undefined;
  clear_invalid?: boolean | undefined;
  moderation?: string | undefined;
  notification_url?: string | undefined;
  ocr?: string | undefined;
  on_success?: string | undefined;
  overwrite?: boolean | undefined;
  phash?: boolean | undefined;
  proxy?: string | undefined;
  public_id?: string | undefined;
  public_id_prefix?: string | undefined;
  quality_analysis?: boolean | undefined;
  raw_convert?: string | undefined;
  regions?: string | { [k: string]: Array<Array<number>> } | undefined;
  responsive_breakpoints?:
    | Array<ResponsiveBreakpoint>
    | ResponsiveBreakpoint
    | undefined;
  return_delete_token?: boolean | undefined;
  upload_preset?: string | undefined;
  use_asset_folder_as_public_id_prefix?: boolean | undefined;
  use_filename?: boolean | undefined;
  use_filename_as_display_name?: boolean | undefined;
  unique_display_name?: boolean | undefined;
  unique_filename?: boolean | undefined;
  visual_search?: boolean | undefined;
  tags?: Array<string> | null | undefined;
  context?: { [k: string]: string } | null | undefined;
  eager?: Array<Array<{ [k: string]: any }>> | undefined;
  transformation?: Array<{ [k: string]: any }> | undefined;
  allowed_formats?: Array<string> | undefined;
  headers?: { [k: string]: string } | undefined;
  face_coordinates?: Array<Array<number>> | undefined;
  custom_coordinates?: Array<Array<number>> | undefined;
  type?: UploadDeliveryType | undefined;
};

export const UploadPresetParsedSettings$zodSchema: z.ZodType<
  UploadPresetParsedSettings
> = z.object({
  access_control: z.array(AccessControlItem$zodSchema).optional(),
  access_mode: UploadPresetParsedSettingsAccessMode$zodSchema.optional(),
  accessibility_analysis: z.boolean().optional(),
  allowed_formats: z.array(z.string()).optional(),
  asset_folder: z.string().optional(),
  async: z.boolean().optional(),
  auto_chaptering: z.boolean().optional(),
  auto_tagging: z.number().optional(),
  auto_transcription: z.union([
    z.boolean(),
    z.lazy(() => UploadPresetParsedSettingsAutoTranscription$zodSchema),
  ]).optional(),
  background_removal: z.string().optional(),
  backup: z.boolean().optional(),
  callback: z.string().optional(),
  categorization: z.string().optional(),
  cinemagraph_analysis: z.boolean().optional(),
  clear_invalid: z.boolean().default(false),
  colors: z.boolean().default(false),
  context: z.record(z.string(), z.string()).nullable().optional(),
  custom_coordinates: z.array(z.array(z.number())).optional(),
  detection: z.string().optional(),
  discard_original_filename: z.boolean().optional(),
  display_name: z.string().optional(),
  eager: z.array(z.array(z.record(z.string(), z.any()))).optional(),
  eager_async: z.boolean().optional(),
  eager_notification_url: z.string().optional(),
  eval: z.string().optional(),
  face_coordinates: z.array(z.array(z.number())).optional(),
  faces: z.boolean().optional(),
  filename_override: z.string().optional(),
  folder: z.string().optional(),
  format: z.string().optional(),
  headers: z.record(z.string(), z.string()).optional(),
  invalidate: z.boolean().optional(),
  media_metadata: z.boolean().optional(),
  metadata: StructuredMetadataParam$zodSchema.optional(),
  moderation: z.string().optional(),
  notification_url: z.string().optional(),
  ocr: z.string().optional(),
  on_success: z.string().optional(),
  overwrite: z.boolean().optional(),
  phash: z.boolean().optional(),
  proxy: z.string().optional(),
  public_id: z.string().optional(),
  public_id_prefix: z.string().optional(),
  quality_analysis: z.boolean().optional(),
  raw_convert: z.string().optional(),
  regions: z.union([
    z.string(),
    z.record(z.string(), z.array(z.array(z.int()))),
  ]).optional(),
  responsive_breakpoints: z.union([
    z.array(ResponsiveBreakpoint$zodSchema),
    ResponsiveBreakpoint$zodSchema,
  ]).optional(),
  return_delete_token: z.boolean().optional(),
  tags: z.array(z.string()).nullable().optional(),
  transformation: z.array(z.record(z.string(), z.any())).optional(),
  type: UploadDeliveryType$zodSchema.optional(),
  unique_display_name: z.boolean().optional(),
  unique_filename: z.boolean().optional(),
  upload_preset: z.string().optional(),
  use_asset_folder_as_public_id_prefix: z.boolean().optional(),
  use_filename: z.boolean().optional(),
  use_filename_as_display_name: z.boolean().optional(),
  visual_search: z.boolean().optional(),
}).describe(
  "Parsed preset configuration settings. Composed from base parameters (stable types) plus parsed serializable fields (arrays/objects instead of strings).",
);
