/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fcf7aec9bc10
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  AccessControlItem,
  AccessControlItem$zodSchema,
} from "./accesscontrolitem.js";
import {
  ResponsiveBreakpoint,
  ResponsiveBreakpoint$zodSchema,
} from "./responsivebreakpoint.js";
import {
  StructuredMetadataParam,
  StructuredMetadataParam$zodSchema,
} from "./structuredmetadataparam.js";
import { TagsParam, TagsParam$zodSchema } from "./tagsparam.js";
import {
  UploadDeliveryType,
  UploadDeliveryType$zodSchema,
} from "./uploaddeliverytype.js";

/**
 * Configuration object for automatic video transcription with translation options.
 */
export type UploadPresetInputAutoTranscription = {
  translate?: Array<string> | undefined;
};

export const UploadPresetInputAutoTranscription$zodSchema: z.ZodType<
  UploadPresetInputAutoTranscription
> = z.object({
  translate: z.array(z.string()).optional(),
}).describe(
  "Configuration object for automatic video transcription with translation options.",
);

export type UploadPresetInputAutoTranscriptionUnion =
  | boolean
  | UploadPresetInputAutoTranscription;

export const UploadPresetInputAutoTranscriptionUnion$zodSchema: z.ZodType<
  UploadPresetInputAutoTranscriptionUnion
> = z.union([
  z.boolean(),
  z.lazy(() => UploadPresetInputAutoTranscription$zodSchema),
]);

/**
 * Deprecated. Use access_control instead. Allows the asset to behave as if it's of the authenticated delivery type while still using the default 'upload' type in delivery URLs. The asset can later be made public by changing its access_mode via the Admin API, without having to update any delivery URLs.
 *
 * @remarks
 *
 * @deprecated enum: The access_mode parameter is no longer supported. To restrict access to assets, you can use the access_control parameter.. Use access_control instead.
 */
export const UploadPresetInputAccessMode = {
  Public: "public",
  Authenticated: "authenticated",
} as const;
/**
 * Deprecated. Use access_control instead. Allows the asset to behave as if it's of the authenticated delivery type while still using the default 'upload' type in delivery URLs. The asset can later be made public by changing its access_mode via the Admin API, without having to update any delivery URLs.
 *
 * @remarks
 *
 * @deprecated enum: The access_mode parameter is no longer supported. To restrict access to assets, you can use the access_control parameter.. Use access_control instead.
 */
export type UploadPresetInputAccessMode = ClosedEnum<
  typeof UploadPresetInputAccessMode
>;

export const UploadPresetInputAccessMode$zodSchema = z.enum([
  "public",
  "authenticated",
]).describe(
  "Deprecated. Use access_control instead. Allows the asset to behave as if it's of the authenticated delivery type while still using the default 'upload' type in delivery URLs. The asset can later be made public by changing its access_mode via the Admin API, without having to update any delivery URLs.\n",
);

/**
 * Named region coordinate groups for cropping with region gravity.
 *
 * @remarks
 * Can be a JSON-encoded string or an object. Each region name may contain
 * only letters, numbers, or hyphens, and must have at least two coordinate pairs.
 */
export type UploadPresetInputRegions = string | {
  [k: string]: Array<Array<number>>;
};

export const UploadPresetInputRegions$zodSchema: z.ZodType<
  UploadPresetInputRegions
> = z.union([
  z.string(),
  z.record(z.string(), z.array(z.array(z.int()))),
]).describe(
  "Named region coordinate groups for cropping with region gravity.\nCan be a JSON-encoded string or an object. Each region name may contain\nonly letters, numbers, or hyphens, and must have at least two coordinate pairs.\n",
);

/**
 * Settings to automatically generate breakpoints for responsive images.
 */
export type UploadPresetInputResponsiveBreakpoints =
  | Array<ResponsiveBreakpoint>
  | ResponsiveBreakpoint;

export const UploadPresetInputResponsiveBreakpoints$zodSchema: z.ZodType<
  UploadPresetInputResponsiveBreakpoints
> = z.union([
  z.array(ResponsiveBreakpoint$zodSchema),
  ResponsiveBreakpoint$zodSchema,
]).describe(
  "Settings to automatically generate breakpoints for responsive images.",
);

export const ParameterWhitelistEnum = {
  None: "none",
} as const;
export type ParameterWhitelistEnum = ClosedEnum<typeof ParameterWhitelistEnum>;

export const ParameterWhitelistEnum$zodSchema = z.enum([
  "none",
]);

/**
 * The parameters that are allowed to be used in an upload request utilizing this preset. If not specified or empty array, all parameters are allowed. If "none", no parameters are allowed.
 *
 * @remarks
 */
export type ParameterWhitelist = Array<string> | ParameterWhitelistEnum;

export const ParameterWhitelist$zodSchema: z.ZodType<ParameterWhitelist> = z
  .union([
    z.array(z.string()),
    ParameterWhitelistEnum$zodSchema,
  ]).describe(
    "The parameters that are allowed to be used in an upload request utilizing this preset. If not specified or empty array, all parameters are allowed. If \"none\", no parameters are allowed.\n",
  );

/**
 * Upload preset configuration for create/update. Settings are sent as top-level string-encoded properties.
 */
export type UploadPresetInput = {
  accessibility_analysis?: boolean | undefined;
  asset_folder?: string | undefined;
  async?: boolean | undefined;
  auto_chaptering?: boolean | undefined;
  auto_tagging?: number | undefined;
  auto_transcription?: boolean | UploadPresetInputAutoTranscription | undefined;
  access_control?: Array<AccessControlItem> | undefined;
  access_mode?: UploadPresetInputAccessMode | undefined;
  backup?: boolean | undefined;
  background_removal?: string | undefined;
  callback?: string | undefined;
  categorization?: string | undefined;
  cinemagraph_analysis?: boolean | undefined;
  colors?: boolean | undefined;
  detection?: string | undefined;
  discard_original_filename?: boolean | undefined;
  display_name?: string | undefined;
  eager_async?: boolean | undefined;
  eager_notification_url?: string | undefined;
  eval?: string | undefined;
  faces?: boolean | undefined;
  filename_override?: string | undefined;
  folder?: string | undefined;
  format?: string | undefined;
  invalidate?: boolean | undefined;
  media_metadata?: boolean | undefined;
  metadata?: StructuredMetadataParam | undefined;
  clear_invalid?: boolean | undefined;
  moderation?: string | undefined;
  notification_url?: string | undefined;
  ocr?: string | undefined;
  on_success?: string | undefined;
  overwrite?: boolean | undefined;
  phash?: boolean | undefined;
  proxy?: string | undefined;
  public_id?: string | undefined;
  public_id_prefix?: string | undefined;
  quality_analysis?: boolean | undefined;
  raw_convert?: string | undefined;
  regions?: string | { [k: string]: Array<Array<number>> } | undefined;
  responsive_breakpoints?:
    | Array<ResponsiveBreakpoint>
    | ResponsiveBreakpoint
    | undefined;
  return_delete_token?: boolean | undefined;
  upload_preset?: string | undefined;
  use_asset_folder_as_public_id_prefix?: boolean | undefined;
  use_filename?: boolean | undefined;
  use_filename_as_display_name?: boolean | undefined;
  unique_display_name?: boolean | undefined;
  unique_filename?: boolean | undefined;
  visual_search?: boolean | undefined;
  tags?: TagsParam | undefined;
  context?: string | undefined;
  eager?: string | undefined;
  transformation?: string | undefined;
  allowed_formats?: string | undefined;
  headers?: string | undefined;
  face_coordinates?: string | undefined;
  custom_coordinates?: string | undefined;
  type?: UploadDeliveryType | undefined;
  name?: string | undefined;
  disallow_public_id?: boolean | undefined;
  unsigned?: boolean | undefined;
  parameter_whitelist?: Array<string> | ParameterWhitelistEnum | undefined;
};

export const UploadPresetInput$zodSchema: z.ZodType<UploadPresetInput> = z
  .object({
    access_control: z.array(AccessControlItem$zodSchema).optional(),
    access_mode: UploadPresetInputAccessMode$zodSchema.optional(),
    accessibility_analysis: z.boolean().optional(),
    allowed_formats: z.string().optional(),
    asset_folder: z.string().optional(),
    async: z.boolean().optional(),
    auto_chaptering: z.boolean().optional(),
    auto_tagging: z.number().optional(),
    auto_transcription: z.union([
      z.boolean(),
      z.lazy(() => UploadPresetInputAutoTranscription$zodSchema),
    ]).optional(),
    background_removal: z.string().optional(),
    backup: z.boolean().optional(),
    callback: z.string().optional(),
    categorization: z.string().optional(),
    cinemagraph_analysis: z.boolean().optional(),
    clear_invalid: z.boolean().default(false),
    colors: z.boolean().default(false),
    context: z.string().optional(),
    custom_coordinates: z.string().optional(),
    detection: z.string().optional(),
    disallow_public_id: z.boolean().optional(),
    discard_original_filename: z.boolean().optional(),
    display_name: z.string().optional(),
    eager: z.string().optional(),
    eager_async: z.boolean().optional(),
    eager_notification_url: z.string().optional(),
    eval: z.string().optional(),
    face_coordinates: z.string().optional(),
    faces: z.boolean().optional(),
    filename_override: z.string().optional(),
    folder: z.string().optional(),
    format: z.string().optional(),
    headers: z.string().optional(),
    invalidate: z.boolean().optional(),
    media_metadata: z.boolean().optional(),
    metadata: StructuredMetadataParam$zodSchema.optional(),
    moderation: z.string().optional(),
    name: z.string().optional(),
    notification_url: z.string().optional(),
    ocr: z.string().optional(),
    on_success: z.string().optional(),
    overwrite: z.boolean().optional(),
    parameter_whitelist: z.union([
      z.array(z.string()),
      ParameterWhitelistEnum$zodSchema,
    ]).optional(),
    phash: z.boolean().optional(),
    proxy: z.string().optional(),
    public_id: z.string().optional(),
    public_id_prefix: z.string().optional(),
    quality_analysis: z.boolean().optional(),
    raw_convert: z.string().optional(),
    regions: z.union([
      z.string(),
      z.record(z.string(), z.array(z.array(z.int()))),
    ]).optional(),
    responsive_breakpoints: z.union([
      z.array(ResponsiveBreakpoint$zodSchema),
      ResponsiveBreakpoint$zodSchema,
    ]).optional(),
    return_delete_token: z.boolean().optional(),
    tags: TagsParam$zodSchema.optional(),
    transformation: z.string().optional(),
    type: UploadDeliveryType$zodSchema.optional(),
    unique_display_name: z.boolean().optional(),
    unique_filename: z.boolean().optional(),
    unsigned: z.boolean().optional(),
    upload_preset: z.string().optional(),
    use_asset_folder_as_public_id_prefix: z.boolean().optional(),
    use_filename: z.boolean().optional(),
    use_filename_as_display_name: z.boolean().optional(),
    visual_search: z.boolean().optional(),
  }).describe(
    "Upload preset configuration for create/update. Settings are sent as top-level string-encoded properties.",
  );
