/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  AccessControlItem,
  AccessControlItem$zodSchema,
} from "./accesscontrolitem.js";

/**
 * Configuration object for automatic video transcription with translation options.
 */
export type AutoTranscription = { translate?: Array<string> | undefined };

export const AutoTranscription$zodSchema: z.ZodType<AutoTranscription> = z
  .object({
    translate: z.array(z.string()).optional(),
  }).describe(
    "Configuration object for automatic video transcription with translation options.",
  );

export type AutoTranscriptionUnion = boolean | AutoTranscription;

export const AutoTranscriptionUnion$zodSchema: z.ZodType<
  AutoTranscriptionUnion
> = z.union([
  z.boolean(),
  z.lazy(() => AutoTranscription$zodSchema),
]);

export type ResponsiveBreakpoint = {
  create_derived?: boolean | undefined;
  max_width?: number | undefined;
  min_width?: number | undefined;
  bytes_step?: number | undefined;
  max_images?: number | undefined;
  transformation?: string | undefined;
};

export const ResponsiveBreakpoint$zodSchema: z.ZodType<ResponsiveBreakpoint> = z
  .object({
    bytes_step: z.int().optional(),
    create_derived: z.boolean().optional(),
    max_images: z.int().optional(),
    max_width: z.int().optional(),
    min_width: z.int().optional(),
    transformation: z.string().optional(),
  });

/**
 * The delivery type that defines if and how the uploaded asset is available for public delivery. By default, all uploaded assets are public (upload). Possible values are upload, authenticated, private or asset.
 */
export const Type = {
  Upload: "upload",
  Authenticated: "authenticated",
  Private: "private",
  Asset: "asset",
} as const;
/**
 * The delivery type that defines if and how the uploaded asset is available for public delivery. By default, all uploaded assets are public (upload). Possible values are upload, authenticated, private or asset.
 */
export type Type = ClosedEnum<typeof Type>;

export const Type$zodSchema = z.enum([
  "upload",
  "authenticated",
  "private",
  "asset",
]).describe(
  "The delivery type that defines if and how the uploaded asset is available for public delivery. By default, all uploaded assets are public (upload). Possible values are upload, authenticated, private or asset.",
);

/**
 * Allows the asset to behave as if it's of the authenticated 'type' (see above) while still using the default 'upload' type in delivery URLs. The asset can later be made public by changing its access_mode via the Admin API, without having to update any delivery URLs. Valid values: public, and authenticated.
 *
 * @remarks
 *
 * @deprecated enum: The access_mode parameter is no longer supported. To restrict access to assets, you can use the access_control parameter.. Use access_control instead.
 */
export const AccessMode = {
  Public: "public",
  Authenticated: "authenticated",
} as const;
/**
 * Allows the asset to behave as if it's of the authenticated 'type' (see above) while still using the default 'upload' type in delivery URLs. The asset can later be made public by changing its access_mode via the Admin API, without having to update any delivery URLs. Valid values: public, and authenticated.
 *
 * @remarks
 *
 * @deprecated enum: The access_mode parameter is no longer supported. To restrict access to assets, you can use the access_control parameter.. Use access_control instead.
 */
export type AccessMode = ClosedEnum<typeof AccessMode>;

export const AccessMode$zodSchema = z.enum([
  "public",
  "authenticated",
]).describe(
  "Allows the asset to behave as if it's of the authenticated 'type' (see above) while still using the default 'upload' type in delivery URLs. The asset can later be made public by changing its access_mode via the Admin API, without having to update any delivery URLs. Valid values: public, and authenticated.\n",
);

export const ParameterWhitelistEnum = {
  None: "none",
} as const;
export type ParameterWhitelistEnum = ClosedEnum<typeof ParameterWhitelistEnum>;

export const ParameterWhitelistEnum$zodSchema = z.enum([
  "none",
]);

/**
 * The parameters that are allowed be used in an upload request utilizing this preset. If not specified or empty array, all parameters are allowed. If "none", no parameters are allowed.
 *
 * @remarks
 */
export type ParameterWhitelist = Array<string> | ParameterWhitelistEnum;

export const ParameterWhitelist$zodSchema: z.ZodType<ParameterWhitelist> = z
  .union([
    z.array(z.string()),
    ParameterWhitelistEnum$zodSchema,
  ]).describe(
    "The parameters that are allowed be used in an upload request utilizing this preset. If not specified or empty array, all parameters are allowed. If \"none\", no parameters are allowed.\n",
  );

export type UploadPreset = {
  accessibility_analysis?: boolean | undefined;
  asset_folder?: string | undefined;
  async?: boolean | undefined;
  auto_chaptering?: boolean | undefined;
  auto_transcription?: boolean | AutoTranscription | undefined;
  cinemagraph_analysis?: boolean | undefined;
  colors?: boolean | undefined;
  context?: string | undefined;
  custom_coordinates?: string | undefined;
  display_name?: string | undefined;
  eager?: string | undefined;
  eager_async?: boolean | undefined;
  eager_notification_url?: string | undefined;
  face_coordinates?: string | undefined;
  faces?: boolean | undefined;
  headers?: string | undefined;
  invalidate?: boolean | undefined;
  media_metadata?: boolean | undefined;
  metadata?: string | undefined;
  moderation?: string | undefined;
  notification_url?: string | undefined;
  phash?: boolean | undefined;
  quality_analysis?: boolean | undefined;
  regions?: string | undefined;
  responsive_breakpoints?: Array<ResponsiveBreakpoint> | undefined;
  tags?: string | undefined;
  callback?: string | undefined;
  backup?: boolean | undefined;
  discard_original_filename?: boolean | undefined;
  overwrite?: boolean | undefined;
  return_delete_token?: boolean | undefined;
  type?: Type | undefined;
  access_mode?: AccessMode | undefined;
  categorization?: string | undefined;
  ocr?: string | undefined;
  raw_convert?: string | undefined;
  background_removal?: string | undefined;
  public_id?: string | undefined;
  transformation?: string | undefined;
  format?: string | undefined;
  proxy?: string | undefined;
  folder?: string | undefined;
  allowed_formats?: string | undefined;
  auto_tagging?: number | undefined;
  access_control?: Array<AccessControlItem> | undefined;
  eval?: string | undefined;
  detection?: string | undefined;
  filename_override?: string | undefined;
  public_id_prefix?: string | undefined;
  use_asset_folder_as_public_id_prefix?: boolean | undefined;
  unique_display_name?: boolean | undefined;
  visual_search?: boolean | undefined;
  use_filename_as_display_name?: boolean | undefined;
  use_filename?: boolean | undefined;
  unique_filename?: boolean | undefined;
  upload_preset?: string | undefined;
  on_success?: string | undefined;
  name?: string | undefined;
  disallow_public_id?: boolean | undefined;
  unsigned?: boolean | undefined;
  parameter_whitelist?: Array<string> | ParameterWhitelistEnum | undefined;
};

export const UploadPreset$zodSchema: z.ZodType<UploadPreset> = z.object({
  access_control: z.array(AccessControlItem$zodSchema).optional(),
  access_mode: AccessMode$zodSchema.optional(),
  accessibility_analysis: z.boolean().optional(),
  allowed_formats: z.string().optional(),
  asset_folder: z.string().optional(),
  async: z.boolean().optional(),
  auto_chaptering: z.boolean().optional(),
  auto_tagging: z.number().optional(),
  auto_transcription: z.union([
    z.boolean(),
    z.lazy(() => AutoTranscription$zodSchema),
  ]).optional(),
  background_removal: z.string().optional(),
  backup: z.boolean().optional(),
  callback: z.string().optional(),
  categorization: z.string().optional(),
  cinemagraph_analysis: z.boolean().optional(),
  colors: z.boolean().default(false),
  context: z.string().optional(),
  custom_coordinates: z.string().optional(),
  detection: z.string().optional(),
  disallow_public_id: z.boolean().optional(),
  discard_original_filename: z.boolean().optional(),
  display_name: z.string().optional(),
  eager: z.string().optional(),
  eager_async: z.boolean().optional(),
  eager_notification_url: z.string().optional(),
  eval: z.string().optional(),
  face_coordinates: z.string().optional(),
  faces: z.boolean().optional(),
  filename_override: z.string().optional(),
  folder: z.string().optional(),
  format: z.string().optional(),
  headers: z.string().optional(),
  invalidate: z.boolean().optional(),
  media_metadata: z.boolean().optional(),
  metadata: z.string().optional(),
  moderation: z.string().optional(),
  name: z.string().optional(),
  notification_url: z.string().optional(),
  ocr: z.string().optional(),
  on_success: z.string().optional(),
  overwrite: z.boolean().optional(),
  parameter_whitelist: z.union([
    z.array(z.string()),
    ParameterWhitelistEnum$zodSchema,
  ]).optional(),
  phash: z.boolean().optional(),
  proxy: z.string().optional(),
  public_id: z.string().optional(),
  public_id_prefix: z.string().optional(),
  quality_analysis: z.boolean().optional(),
  raw_convert: z.string().optional(),
  regions: z.string().optional(),
  responsive_breakpoints: z.array(z.lazy(() => ResponsiveBreakpoint$zodSchema))
    .optional(),
  return_delete_token: z.boolean().optional(),
  tags: z.string().optional(),
  transformation: z.string().optional(),
  type: Type$zodSchema.optional(),
  unique_display_name: z.boolean().optional(),
  unique_filename: z.boolean().optional(),
  unsigned: z.boolean().optional(),
  upload_preset: z.string().optional(),
  use_asset_folder_as_public_id_prefix: z.boolean().optional(),
  use_filename: z.boolean().optional(),
  use_filename_as_display_name: z.boolean().optional(),
  visual_search: z.boolean().optional(),
});
