/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UploadPresetCreateResponse = {
  message: string;
  name: string;
  external_id: string;
};

export const UploadPresetCreateResponse$zodSchema: z.ZodType<
  UploadPresetCreateResponse
> = z.object({
  external_id: z.string().describe(
    "The unique identifier for the upload preset.",
  ),
  message: z.string().describe("The result message."),
  name: z.string().describe("The name of the created upload preset."),
});
