/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const UriType$zodSchema = z.enum([
  "webhook",
  "flow",
]);

export type UriType = z.infer<typeof UriType$zodSchema>;
